[Programmers-heap] jiwoo
soo5717/2021-Algorithm-Study pull request #29
Opened 2021-05-28 08:59 UTC by jjuyaa

2021-05-29 22:51 UTC, soo5717 requested changes

2021-05-29 22:51 UTC, soo5717 commented on Programmers/jiwoo/heap/더맵게.py
> +            return -1
이번 문제의 경우 복잡하지 않아서 예외처리로 해결해도 되지만, 다른 경우에서는 사용자가 의도한대로 작동하지 않을 수 있으니 다른 방식으로 해결하는 풀이도 시도해보는 것을 추천한다.

예외처리로 해결한다는 생각은 새로워서 좋았음.

2021-05-29 22:51 UTC, soo5717 commented on Programmers/jiwoo/heap/이중우선순위큐.py
> +            heapq.heappush(max_heap, (num*-1, num))
`num * -1`로 표기할 필요 없이 `-num`이라 표기하는 것이 더 나을 것 같다.

2021-05-29 22:51 UTC, soo5717 commented on Programmers/jiwoo/heap/이중우선순위큐.py
> +                pass
`if not heap`으로 고치는게 더 파이써닉한 코드일 것 같다.

2021-05-29 22:51 UTC, soo5717 commented on Programmers/jiwoo/heap/이중우선순위큐.py
> +    max_heap = []
유진이처럼 min heap, max heap으로 표기하는 것이 좀 더 명시적일 것 같다.

2021-05-29 22:51 UTC, soo5717 commented on Programmers/jiwoo/heap/이중우선순위큐.py
> +        return [0, 0]
if else 문은 삼항연산자로 표현하면 한 줄로 표현 가능하니 이 부분은 수정했으면 한다.

2021-05-29 22:51 UTC, soo5717 commented on Programmers/jiwoo/heap/이중우선순위큐.py
> +                max_heap.remove((min_num*(-1), min_num))
heapify를 사용해서 문제를 해결했던 것이 시간복잡도 측면에서 별로 좋지 않은 선택이라고 생각했는데 max heap과 min heap으로 나누어서도 크게 복잡하지 않은 알고리즘으로도 문제를 해결할 수 있는 방법을 볼 수 있어 좋았음. remove를 사용해서 min과 max heap을 동기화하는 발상이 참신했음!

하지만 remove의 경우도 `O(n)`의 시간복잡도를 가지는 것으로 알고 있어 유진이 방식도 참고해봐도 좋을 것 같다.

2021-05-29 22:58 UTC, soo5717 commented on Programmers/jiwoo/heap/디스크컨트롤러.py
> +                heapq.heappush(heap, [j[1], j[0]])
매번 jobs의 길이만큼 반복을 해야 해서 시간적으로 비효율적인 느낌이 든다.
deque를 사용해서 해결하거나 다른 방식을 생각해봐도 좋을 것 같다.

실제 deque를 사용한 코드와 비교를 해봤을 때 실행 시간 차이가 꽤 나는 것을 볼 수 있었음.

2021-05-29 22:59 UTC, soo5717 commented on Programmers/jiwoo/heap/디스크컨트롤러.py
> +        if len(heap) > 0:
여기도 len 보다는 `if heap`으로 고쳐서 표현하는게 좋을 듯

2021-05-29 22:59 UTC, soo5717 commented on Programmers/jiwoo/heap/디스크컨트롤러.py
> +    return int(time/len(jobs))
굳이 int를 사용할 필요 없이 //를 사용하면 된다.

2021-05-29 23:02 UTC, soo5717 commented on Programmers/jiwoo/heap/디스크컨트롤러.py
> +            disk = heapq.heappop(heap)
disk[0], disk[1] 이렇게 표현하는 것 대신 변수를 `time, call = heapq.heappop(heap)` 이렇게 쓰는 것도 가능하다.

2021-05-29 23:04 UTC, soo5717 commented on Programmers/jiwoo/heap/디스크컨트롤러.py
> +    start, time, now, i = -1, 0, 0, 0
변수가 의미하는 것에 대해서 주석을 달아두면 추후 보기 편할 것 같다.

2021-05-29 23:05 UTC, soo5717 commented on Programmers/jiwoo/heap/디스크컨트롤러.py
> +    return int(time/len(jobs))
기본적으로 내 풀이 방식이랑 유사하지만 그 안에서 조금씩 다른 방식이 있어서 비교해볼 수 있어 좋았다.

2021-05-30 15:12 UTC, eugene-tp commented on Programmers/jiwoo/heap/더맵게.py
> +            return -1
마찬가지로 예외처리를 코테에 사용해본 게 신기했다.
하지만 여러모로 다양한 문제에 적용은 불가능 할 것 같다!

2021-05-30 15:12 UTC, eugene-tp commented on Programmers/jiwoo/heap/이중우선순위큐.py
> +                pass
pass가 코테에 적용된 걸 처음 봐서 신기했다.
pass는 밑에 있는 코드도 실행하게 되니까 continue와의 기능을 명확하게 이해하고 사용해야 할 것 같다.
해당 영역에서는 if-elif-else로만 구성되어 있어 문제는 없지만
그 아래에 따로 분리된 코드가 있었다면 continue와 다른 기능을 했을 것!(신기 :))

2021-05-30 15:12 UTC, eugene-tp commented on Programmers/jiwoo/heap/디스크컨트롤러.py
> +    return int(time/len(jobs))
몫이 필요할 때 계속 int(x/y)로 사용하는 습관이 있는 것 같다!
//를 습관화하면 편할듯.

2021-06-16 05:27 UTC, jjuyaa commented on Programmers/jiwoo/heap/디스크컨트롤러.py
> +                heapq.heappush(heap, [j[1], j[0]])
참고할게! deque은 익숙하지 않아서 계속 다른 방법 먼저 사용하는 것 같지만,, 해보겠슴다!

2021-06-16 05:27 UTC, merged