[Programmers-2019_kakao_blind] jiwoo
soo5717/2021-Algorithm-Study pull request #42
Opened 2021-07-15 13:11 UTC by jjuyaa

2021-07-17 19:27 UTC, soo5717 requested changes

2021-07-17 19:27 UTC, soo5717 commented on Programmers/jiwoo/2019_kakao_blind/실패율.py
> +            count = stages.count(i)
count를 쓰면 시간 복잡도가 `O(n^2)`이 되기 때문에 count 방식말고 미리 각 stage의 사용자를 세는 방식을 활용하는게 더 좋을 듯 함!!

라이브러리나 함수를 사용하면 코드가 간결해지지만 시간 복잡도까지 고려해서 사용하는 습관을 기르면 더 좋을 듯 함!

2021-07-17 19:27 UTC, soo5717 commented on Programmers/jiwoo/2019_kakao_blind/실패율.py
> +            count = stages.count(i)
이 부분은 코드 변경 후에 머지했으면 함

2021-07-17 19:27 UTC, soo5717 commented on Programmers/jiwoo/2019_kakao_blind/오픈채팅방.py
> +        record_split = record.split(' ')
굳이 `split(' ')`이라 작성하지 않고 `split()`으로 작성해도 동일한 기능을 하니 참고하면 좋을 듯 함.

2021-07-17 19:27 UTC, soo5717 commented on Programmers/jiwoo/2019_kakao_blind/오픈채팅방.py
> +            result.append(comment)
간단한 코드이기 때문에 굳이 comment 변수에 문자열을 할당하지 않고 바로 append해도 좋을 듯 함.

2021-07-17 19:27 UTC, soo5717 commented on Programmers/jiwoo/2019_kakao_blind/후보키.py
> +    col = len(relations[0])
row, col의 길이를 미리 선언해둔 것이 좋아보임! 다음 코드 작성 시에 참고하겠음.

2021-07-17 19:27 UTC, soo5717 commented on Programmers/jiwoo/2019_kakao_blind/후보키.py
> +        candidates[i] = combinations(range(col), i)
리스트의 차원이 많아질 수록 시간이 더 걸리기 때문에 반복문을 따로 분리할 필요 없이 아래 반복문 내에서 해결하는게 더 나을 듯 함.

2021-07-17 19:27 UTC, soo5717 commented on Programmers/jiwoo/2019_kakao_blind/후보키.py
> +    return len(min_key)
주석으로 유일성 검사 부분 최소성 검사 부분이라고 적어주면 좋을 듯함.

2021-07-17 19:27 UTC, soo5717 commented on Programmers/jiwoo/2019_kakao_blind/후보키.py
> +                        min_key.append(j)
한 반복문 내에서 해결한 점이 깔끔해서 좋은 것 같음.

2021-07-17 19:27 UTC, soo5717 commented on Programmers/jiwoo/2019_kakao_blind/후보키.py
> +                        if set(r).issubset(set(j)):
set의 `issubset`은 몰랐는데 알아감! 시간이 된다면 참고해서 코드 작성 후 시간 효율을 비교해보겠음.

2021-07-18 17:46 UTC, eugene-tp commented on Programmers/jiwoo/2019_kakao_blind/오픈채팅방.py
> +            result.append(comment)
동의. 이건 취향일 수 있지만 난이도에 따라 표현 달라지면 좋을 듯

2021-07-18 17:46 UTC, eugene-tp commented on Programmers/jiwoo/2019_kakao_blind/실패율.py
> +            count = stages.count(i)
동의한다. count는 유용할 때는 참 좋지만, 꼭 써야 하거나 쓰지 않으면 너무 복잡해질 때 사용하는 게 좋을 듯 함

2021-07-18 17:46 UTC, eugene-tp commented on Programmers/jiwoo/2019_kakao_blind/실패율.py
> +            users -= count
무의식적으로 더할 생각만 하고 있었는데, 둘 다 -로 접근 한게 신기하다.

2021-07-18 17:46 UTC, eugene-tp commented on Programmers/jiwoo/2019_kakao_blind/후보키.py
> +                        if set(r).issubset(set(j)):
부분집합 함수라니..역시 강력한 파이썬
또 하나 배워갑니다..

2021-07-18 17:46 UTC, eugene-tp commented on Programmers/jiwoo/2019_kakao_blind/후보키.py
> +                        if set(r).issubset(set(j)):
어느정도 길이가 있고 for문 안으로도 많이 들어가면서 이어지는데, i j k r s 로만 표현되어 이해에 어려움이 다소 있다.
아래 수연이 말처럼, 주석 또는 변수 재설정을 해주면 좋을 것 같다.

2021-07-21 09:22 UTC, merged