[Baekjoon-19_week] eugene
soo5717/2021-Algorithm-Study pull request #59
Opened 2021-09-02 15:45 UTC by eugene-tp

2021-09-04 01:33 UTC, soo5717 commented on Baekjoon/eugene/19_week/지구 온난화.py
> +                    y_start, y_end = min(y, y_start), max(y,y_end)
반복문을 추가로 돌지 않고 여기에 넣은 부분이 좋았다.
min, max를 활용해서 코드를 작성해서 더 간결하고 명확한 느낌이다.
참고해서 내 코드도 이런 방식으로 변경해보려고 함!

2021-09-04 01:33 UTC, soo5717 commented on Baekjoon/eugene/19_week/지구 온난화.py
> +        print(answer[x_idx][y_start:y_end+1])
연산자 쓸 때 띄어쓰기 해주세요!

2021-09-04 01:44 UTC, soo5717 requested changes

2021-09-04 01:44 UTC, soo5717 commented on Baekjoon/eugene/19_week/지구 온난화.py
> +                    answer[x]=str(answer[x][:y]+answer[0][0]+answer[x][y+1:])
시간이 더 나오는 이유가 무엇일까 고민했는데 여기서 문자열 처리를 할 때 시간이 더 걸리는 것 아닐까 추측 중

2021-09-04 01:44 UTC, soo5717 commented on Baekjoon/eugene/19_week/지구 온난화.py
> +                    y_start, y_end = min(y, y_start), max(y,y_end)
반복문을 추가로 돌지 않고 여기에 넣은 부분이 좋았다.
min, max를 활용해서 코드를 작성해서 더 간결하고 명확한 느낌이다.
참고해서 내 코드도 이런 방식으로 변경해보려고 함!

2021-09-04 01:44 UTC, soo5717 commented on Baekjoon/eugene/19_week/지구 온난화.py
> +        print(answer[x_idx][y_start:y_end+1])
연산자 쓸 때 띄어쓰기 해주세요!

2021-09-04 01:44 UTC, soo5717 commented on Baekjoon/eugene/19_week/지구 온난화.py
> +            if mapInfo[x][y] == 'X':
이 부분을 아래처럼 변경하면 아래 코드에 대해서 들여쓰기를 안 해도 된다!
```python
if mapInfo[x][y] == '.':
    continue
```

2021-09-04 01:44 UTC, soo5717 commented on Baekjoon/eugene/19_week/지구 온난화.py
> +            if mapInfo[x][y] == 'X':
변수명 스네이크 케이스로 작성하자!!!!!! 카멜과 스네이크 혼용하지 않기

2021-09-04 01:44 UTC, soo5717 commented on Baekjoon/eugene/19_week/지구 온난화.py
> +    y_start, y_end = C+10, 0
10을 더한 이유가 뭘까?

2021-09-04 01:44 UTC, soo5717 commented on Baekjoon/eugene/19_week/지구 온난화.py
> +                if mapInfo[x+1][y] =='.': cnt+=1
`or`을 사용해서 한 줄로 작성하는 것과 이렇게 명시적으로 보기 편하게 작성하는 것 중 뭐가 더 나은 걸까?

2021-09-04 01:44 UTC, soo5717 commented on Baekjoon/eugene/19_week/지구 온난화.py
> +                if mapInfo[x+1][y] =='.': cnt+=1
나는 `or`을 사용하는 편

2021-09-04 01:44 UTC, soo5717 commented on Baekjoon/eugene/19_week/지구 온난화.py
> +        print(answer[x_idx][y_start:y_end+1])
항상 말하지만 변수나 띄어쓰기 신경써주세요..!!!

2021-09-06 00:43 UTC, eugene-tp commented on Baekjoon/eugene/19_week/지구 온난화.py
> +                if mapInfo[x+1][y] =='.': cnt+=1
or를 사용하면 반복문을 써줘야 해서, 보기 편하게 나열해줬음!. mapInfo[i][j]의 i와 j에 위치를 매번 변경해주는 과정도 귀찮았음..!

2021-09-06 00:44 UTC, eugene-tp commented on Baekjoon/eugene/19_week/지구 온난화.py
> +    y_start, y_end = C+10, 0
발표할 때는 R+3이었음! 기본으로 주어지는 map에서 테두리를 둘렀기 때문에 +2 이상이기만 해도 괜찮지만 그냥 임의의 수를 넣었음

2021-09-06 00:53 UTC, merged