[Baekjoon-19_week] jiwoo
soo5717/2021-Algorithm-Study pull request #60
Opened 2021-09-04 02:02 UTC by jjuyaa

2021-09-04 02:27 UTC, soo5717 requested changes

2021-09-04 02:27 UTC, soo5717 commented on Baekjoon/jiwoo/19_week/지구온난화.py
> +                    count += 1
여기 코드 제가 잘못 썼는데 if랑 elif로 해도 될 것 같아요

2021-09-04 02:27 UTC, soo5717 commented on Baekjoon/jiwoo/19_week/지구온난화.py
> +				end_col = j
유진이처럼 추가 반복문 없이 코드 작성하도록 변경하면 더 좋을 듯합니다!

2021-09-04 02:27 UTC, soo5717 commented on Baekjoon/jiwoo/19_week/지구온난화.py
> +    print(''.join(l[start_col:end_col+1]))
연산자 사이에 띄어쓰기 일관성 지켜주세요!!

2021-09-04 02:27 UTC, soo5717 commented on Baekjoon/jiwoo/19_week/지구온난화.py
> +    print(''.join(l[start_col:end_col+1]))
코드가 동일해서 코드 리뷰는 이 정도만 할게요!

2021-09-06 01:49 UTC, eugene-tp commented on Baekjoon/jiwoo/19_week/지구온난화.py
> +    print(''.join(l[start_col:end_col+1]))
동일해서 스킵

2021-09-11 03:05 UTC, merged