[Baekjoon/Programmers-25_week] jiwoo
soo5717/2021-Algorithm-Study pull request #78
Opened 2021-11-23 01:10 UTC by jjuyaa

2021-11-24 17:47 UTC, eugene-tp commented on 단어수학.py
> +            alpha_count_list[word_list[i][j]] = 10 ** (len(word_list[i]) - j - 1)
계속 word_list 길이를 사용할거면 변수로 빼도 좋을 것 같다.

2021-11-24 17:47 UTC, eugene-tp commented on 단어수학.py
> +sum_list.sort(reverse = True)
sum_list 없이 alpha_count_list를 바로 정렬해도 좋을 것 같다

2021-11-24 17:47 UTC, eugene-tp commented on Programmers/jiwoo/25_week/거리두기 확인하기.py
> +                            break
i,j 가 영역을 벗어난 경우는 한번에 if 로 정리하고 continue로 넘겨주면 될 것 같다.

2021-11-24 17:47 UTC, eugene-tp commented on Programmers/jiwoo/25_week/거리두기 확인하기.py
> +            test_place.append(list(n))
바로 place를 사용하지 않고 test_place로 대체한 이유가 궁금하다.

2021-11-25 17:45 UTC, soo5717 requested changes

2021-11-25 17:45 UTC, soo5717 commented on Programmers/jiwoo/25_week/거리두기 확인하기.py
> +    return answer
solution에서만 작성하지 말고 함수로 분리해주면 좋을 것 같아요! 물론 코테 볼 때는 시간이 없어서 정신이 없겠지만 평소에라도 함수로 분리해서 작성하는 습관을 가져봅시다.

2021-11-25 17:45 UTC, soo5717 commented on 단어수학.py
> +    cal_num -= 1
유진이처럼 enumerate를 활용해도 좋을 것 같아요~

2021-11-25 17:45 UTC, soo5717 commented on Programmers/jiwoo/25_week/거리두기 확인하기.py
> +                            break
확실히 빠르게 작성할 수 있는 코드이긴 한데 전체적으로 코드가 길어지다 보니 이해하기가 어려운 면이 있는 것 같아요. 다른 사람 코드 보면서 조금 더 개선해보면 좋을 듯 합니다.

2021-11-28 01:53 UTC, merged