[Baekjoon/Programmers-25_week] eugene
soo5717/2021-Algorithm-Study pull request #79
Opened 2021-11-23 01:16 UTC by eugene-tp

2021-11-25 02:12 UTC, jjuyaa commented on Baekjoon/eugene/25_week/단어 수학.py
> +        alphabet_num[num] += 10**(key-1)
같은 로직인데 간단하게 표현할 수 있는 것이 좋았음

2021-11-25 02:12 UTC, jjuyaa commented on Baekjoon/eugene/25_week/단어 수학.py
> +sorted_alphabet = sorted(alphabet_num.items(), key = lambda item: item[1], reverse=True)
파이썬 답게 따로 배열을 만들지 않고 한 줄로 정렬하고 표현한 점이 좋았음 참고할게요!

2021-11-25 02:12 UTC, jjuyaa commented on Baekjoon/eugene/25_week/단어 수학.py
> +num_list = {i: [] for i in range(10)}
이렇게 표현한 적은 없는데 신기하다 사전 표현할 때 참고하겠습니다

2021-11-25 02:12 UTC, jjuyaa commented on Programmers/eugene/25_week/거리두기 확인하기.py
> +                                    return 0
상대적으로 간단하게 조건들을 처리하고 확인할 수 있어서 이해도 잘 되는 듯 함

2021-11-25 02:12 UTC, jjuyaa commented on Programmers/eugene/25_week/거리두기 확인하기.py
> +    return result
함수로 빼내면 진짜 간단하게 느껴지는 것 같아 좋아요

2021-11-25 17:40 UTC, soo5717 requested changes
전체적으로 로직은 좋았는데 불필요한 ( )나 { }들이 많아서 삭제해주면 좋을 것 같아요!!

2021-11-25 17:40 UTC, soo5717 commented on Programmers/eugene/25_week/거리두기 확인하기.py
> +        result += {rule_check(p)}
rule_check를 { }로 감싼 이유가 있나요?

2021-11-25 17:40 UTC, soo5717 commented on Programmers/eugene/25_week/거리두기 확인하기.py
> +            if i == 'P':
P가 아닌 경우에 continue를 해서 아래 코드는 들여쓰기 없이 작성해도 좋을 것 같아요!

2021-11-25 17:40 UTC, soo5717 commented on Programmers/eugene/25_week/거리두기 확인하기.py
> +                for (mx, my) in manhattan:
( ) 제거해도 동일하게 동작합니다.

2021-11-25 17:40 UTC, soo5717 commented on Programmers/eugene/25_week/거리두기 확인하기.py
> +            if i == 'P':
변수명이 i라서 뭘 뜻하는지 헷갈리는데 조금 더 명시적으로 지어주면 좋을 것 같습니다.

2021-11-25 17:40 UTC, soo5717 commented on Baekjoon/eugene/25_week/단어 수학.py
> +        alphabet_num[value] = 0
defauldict를 사용해서 초기화 해봅시다!

2021-11-25 17:40 UTC, soo5717 commented on Baekjoon/eugene/25_week/단어 수학.py
> +        num_list[len(word) - idx] += {value}
여기에서도 value를 { }로 감싼 이유가 있나요? 없다면 제거해도 동일하게 동작할 것 같아요.

2021-11-25 17:40 UTC, soo5717 commented on Baekjoon/eugene/25_week/단어 수학.py
> +    for num in (num_list[key]):
여기에서도 불필요한 ( )가 있어요

2021-11-25 17:40 UTC, soo5717 commented on Baekjoon/eugene/25_week/단어 수학.py
> +    answer += operand * (9-idx)
idx를 활용해서 바로 9 - idx 한 부분이 좋았습니다! 코드가 더 간결해져서 좋네요~

2021-12-05 08:13 UTC, eugene-tp commented on Programmers/eugene/25_week/거리두기 확인하기.py
> +        result += {rule_check(p)}
TypeError: 'int' object is not iterable
 "+=" 연산자를 사용해서 감싸지 않으면 위와 같은 오류가 발생합니다.
다만, 아래와 같이 사용 가능
result.append(rule_check(p))

2021-12-05 08:18 UTC, merged