[Programmers-27_week] jiwoo
soo5717/2021-Algorithm-Study pull request #85
Opened 2022-01-06 14:15 UTC by jjuyaa

2022-01-09 16:01 UTC, eugene-tp commented on Programmers/jiwoo/27_week/튜플.py
> +    return answer
일부 테스트 케이스의 경우, 다른 사람 코드와 10배 가량 시간이 많이 소요된다. (21 vs 290)
리스트(answer)만 dict을 사용해 코드를 수정하면 시간이 단축된다

2022-01-11 11:32 UTC, soo5717 requested changes
프린트 문 제거 후 다시 올려주세요!

2022-01-11 11:32 UTC, soo5717 commented on Programmers/jiwoo/27_week/튜플.py
> +    s.sort(key = len)
단순한 부분이니 한 줄로 합쳐서 표현해도 좋을 듯 하다.

2022-01-11 11:32 UTC, soo5717 commented on Programmers/jiwoo/27_week/튜플.py
> +                print(answer)
```suggestion
```

2022-01-11 11:32 UTC, soo5717 commented on Programmers/jiwoo/27_week/튜플.py
> +            if int(j) not in answer:
not in 표현은 내부적으로 반복문이기 때문에 주의해서 사용하자. 탐색해야 할 것이 많아질 수록 성능이 떨어질 수 밖에 없는 듯

2022-01-12 14:02 UTC, merged